name: asamba_android
description: 'A new Flutter project.'

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.5.4

dependencies:
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.2.1
  http: ^1.3.0
  intl: ^0.20.2
  liquid_pull_to_refresh: ^3.0.1
  local_auth: ^2.3.0
  lottie: ^3.2.0
  mobile_scanner: ^7.0.1
  month_picker_dialog: ^6.5.0
  pinput: ^5.0.1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/lottie/

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/images/logo.png'
  remove_alpha_ios: true
